apiVersion: apps/v1
kind: Deployment
metadata:
  name: dandel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dandel
  template:
    metadata:
      labels:
        app: dandel
    spec:
      containers:
      - image: okteto.dev/dandel:latest
        name: dandel
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "d460959f-4644-4bf3-9cf4-54121b6135a8"
        - name: Vless_Path
          value: "/d460959f-4644-4bf3-9cf4-54121b6135a8-vless"
        - name: Vmess_UUID
          value: "d460959f-4644-4bf3-9cf4-54121b6135a8"
        - name: Vmess_Path
          value: "/d460959f-4644-4bf3-9cf4-54121b6135a8-vmess"
        - name: Share_Path
          value: "/d460959f-4644-4bf3-9cf4-54121b6135a8-link"
